[toolchain]

[features]
seeds = false
skip-lint = false

[programs.localnet]
favorites = "6KtYKknL6YTnzbfTiMSkm9KQbD8YEVNcjbzUX64a4XUX"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "Localnet"
wallet = "/home/pavlo/.config/solana/id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
